---
- import_tasks: vars.yml
  tags:
    - hostname

- name: set the hostname
  hostname:
    name: "{{ hostname__short }}"
  when: ansible_hostname != hostname__short
  tags:
    - hostname

- name: make the hostname permanent
  copy:
    content: "{{ hostname__fqdn }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags:
    - hostname

- name: remove any extra loopback interface
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    state: absent
  tags:
    - hostname

- name: ensure the localhost entry is configured properly
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost
    state: present
  tags:
    - hostname

- name: ensure hosts entry for primary ip
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostname_ip }}"
    line: "{{ hostname_ip }}{% if hostname__fqdn != '' %}{{ '\t' }}{{ hostname__fqdn }}{% endif %}{{ '\t' }}{{ hostname__short }}"
    state: present
  tags:
    - hostname

