---
- name: set the hostname
  hostname:
    name: "{{ hostname | inventory_hostname_short }}"
  when: ansible_hostname != inventory_hostname_short
  tags:
    - hostname


- name: make the hostname permanent
  copy:
    content: "{{ inventory_hostname_short }}
