---
- name: check for required variables
  fail:
    msg: "Variable '{{ item }}' is required, but undefined"
  when: item not in vars
  with_items:
    - hostname_fqdn
    - hostname_ip

- name: set the short hostname
  set_fact:
    hostname__short: "{% if '.' in hostname_fqdn %}{{ hostname_fqdn.split('.')[0] }}{% else %}{{ hostname_fqdn }}{% endif %}"

- name: set the domain name
  set_fact:
    hostname__domain: "{% if '.' in hostname_fqdn %}{{ hostname_fqdn.split('.', 1)[1] }}{% else %}{{ '' }}{% endif %}"

- name: set the fqdn
  set_fact:
    hostname__fqdn: "{% if '.' in hostname_fqdn %}{{ hostname__short }}.{{ hostname__domain }}{% else %}{{ hostname__short }}{% endif %}"
